### ISSUE TITLE
Contribute docsets to Dash

### ISSUE THREAD

**Issue by Kapeli** [SteveBenner/couchdb-dash-docset#1]
I've set up a repo where users can contribute docsets to Dash. You can check it out at https://github.com/Kapeli/Dash-User-Contributions. It should contain all the info you need to get started.

Docsets that are contributed in this way will appear in a separate User Contributed section under Dash's Preferences > Downloads (i.e. just like the current Ruby Gems or Cocoa Pods sections).

If you need any help with this, don't hesitate to contact me. Thank you!

**Comment by SteveBenner** [comment]
Incredibly cool - thanks for hitting me up! Man has it been bugging me how out of date I am, really want to keep the CouchDB docs up to date but I’m dying here under the workload of my current project. When I do get around to it, I’ll be sure to use your new system, and I am loving the updates to Dash, keep up the incredible work.

**Comment by Kapeli** [comment]
:+1:

**Comment by nolanlawson** [comment]
@SteveBenner What's the status of this? Seems like your TGZ file could just be contributed as-is to Dash. I tried it out, works great! :)

**Comment by SteveBenner** [comment]
Soon. Soon.

**Comment by SteveBenner** [comment]
Well, I feel silly… For a very long time I just put [this](https://github.com/Kapeli/Dash-User-Contributions/pull/462) off because there seemed to be a long checklist for the contribution process, and being someone who is obsessively thorough about such things, I mistakenly thought it would be time consuming.

**NOPE!** Most of the protocol constituted of actions I had already performed in my own repo, and my docset was already compliant with the guidelines. Doh. I should have gotten this submitted months ago, haha!
