### ISSUE TITLE
"Official" CouchDB docset

### ISSUE THREAD

**Issue by Kapeli** [SteveBenner/couchdb-dash-docset#3]
Hi @SteveBenner. This is just a heads-up that a CouchDB docset made by me will be released in the next Dash update.

Please let me know what you would like to happen with your CouchDB docset in the user contributed section? Should I remove it or will you continue to support it alongside my own docset? Either way is fine with me.

If you want to check out my own docset, you can grab it from http://kapeli.com/feeds/CouchDB.tgz. Let me know if you have any comments or notice anything wrong.

**Comment by SteveBenner** [comment]
@Kapeli I appreciate your polite notice and that you haven’t removed my docset. I’d like to keep my docset along with your official one; it wouldn’t be confusing since you have a clear designation in Dash for user contributed material. I do think keeping ‘legacy’ docs for older CouchDB versions is valuable, speaking from personal experience as a developer using CouchDB.

My docset is configured for versioning, as I had intended to keep the docset up-to-date with Apache’s releases… I’ve been caught up in prepping to move for a new job out of country so this has definitely fallen under neglect. In fact someone has helpfully submitted a version 1.6 docset for my consideration and I have yet to check it out. I’m going to be able to update this repo in the near future though :smiley: I plan on posting docsets for every minor version after 1.4.

**Comment by Kapeli** [comment]
No worries :+1:

**Comment by Kapeli** [comment]
@SteveBenner I'm going to remove the docset as it hasn't been updated for over a year. If you'd like the docset to come back to Dash's User Contributed section, please update it.
